spring.config.import=file:./.env[.properties],optional:file:./.local.env[.properties]

spring.application.name=chatbot-msn-msii-25-27

spring.datasource.url=jdbc:postgresql://localhost:5432/db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto = create

spring.sql.init.platform = init
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode = always

spring.ai.google.genai.api-key=${GEMINI_API_KEY:root}

